import PyInstaller.__main__
from pathlib import Path
import shutil
import subprocess
import os

def build():
    # Define the path to the GUI script
    current_dir = Path(__file__).resolve().parent
    script_path = current_dir / "organisr_app" / "gui.py"
    
    # PyInstaller arguments
    args = [
        str(script_path),              # Script to convert
        '--name=FileOrganizerPro',     # Name of the executable
        '--onefile',                   # Create a single executable file
        '--windowed',                  # Run without a console window (GUI mode)
        '--clean',                     # Clean PyInstaller cache
        '--noconfirm',                 # Do not ask for confirmation to overwrite
        f'--distpath={current_dir / "dist"}', # Output directory
        f'--workpath={current_dir / "build"}', # Temporary work directory
        f'--specpath={current_dir}'    # Spec file directory
    ]
    
    print("Starting build process...")
    print(f"Target script: {script_path}")
    try:
        PyInstaller.__main__.run(args)
    except SystemExit:
        pass
    
    exe_path = current_dir / 'dist' / 'FileOrganizerPro.exe'
    print(f"Build complete. Executable located at: {exe_path}")

    # Generate Installer Script
    create_installer(current_dir, exe_path)

def create_installer(base_path, exe_path):
    print("-" * 30)
    print("Generating Installer Script...")
    
    iss_path = base_path / "setup.iss"
    output_dir = base_path / "dist"
    
    # Inno Setup Script Content
    iss_content = f"""; Script generated by build.py

[Setup]
AppName=File Organizer Pro
AppVersion=1.0
AppPublisher=Organisr
DefaultDirName={{autopf}}\\FileOrganizerPro
DefaultGroupName=File Organizer Pro
OutputDir={output_dir}
OutputBaseFilename=FileOrganizerPro_Setup
Compression=lzma
SolidCompression=yes
PrivilegesRequired=lowest
DisableProgramGroupPage=yes

[Files]
Source: "{exe_path}"; DestDir: "{{app}}"; Flags: ignoreversion

[Icons]
Name: "{{group}}\\File Organizer Pro"; Filename: "{{app}}\\FileOrganizerPro.exe"
Name: "{{autodesktop}}\\File Organizer Pro"; Filename: "{{app}}\\FileOrganizerPro.exe"; Tasks: desktopicon

[Tasks]
Name: "desktopicon"; Description: "Create a &desktop icon"; GroupDescription: "Additional icons:"; Flags: unchecked

[Run]
Filename: "{{app}}\\FileOrganizerPro.exe"; Description: "Launch File Organizer Pro"; Flags: nowait postinstall skipifsilent
"""
    
    try:
        with open(iss_path, "w") as f:
            f.write(iss_content)
        print(f"Inno Setup script created at: {iss_path}")
    except Exception as e:
        print(f"Failed to create installer script: {e}")
        return

    # Attempt to compile if Inno Setup is installed
    iscc_path = shutil.which("iscc")
    
    # Check common default paths for Inno Setup on Windows
    if not iscc_path:
        possible_paths = [
            r"C:\Program Files (x86)\Inno Setup 6\ISCC.exe",
            r"C:\Program Files\Inno Setup 6\ISCC.exe"
        ]
        for p in possible_paths:
            if os.path.exists(p):
                iscc_path = p
                break
    
    if iscc_path:
        print(f"Found Inno Setup Compiler at: {iscc_path}")
        print("Compiling installer...")
        try:
            subprocess.run([iscc_path, str(iss_path)], check=True)
            print(f"Installer created successfully: {output_dir / 'FileOrganizerPro_Setup.exe'}")
        except subprocess.CalledProcessError as e:
            print(f"Error compiling installer: {e}")
    else:
        print("Inno Setup Compiler (ISCC) not found.")
        print("To create the installer exe:")
        print("1. Download and install Inno Setup from https://jrsoftware.org/isdl.php")
        print(f"2. Open and compile the generated script: {iss_path}")

if __name__ == "__main__":
    build()